services:
  backend:
    build: ./back
    ports:
      - "5000:5000"
    networks:
      - fullstack-network
    develop:
      watch:
        - action: rebuild
          path: ./back

  frontend:
    build:
      context: ./front
      args:
        - REACT_APP_BACKEND_URL=http://backend:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - fullstack-network
    develop:
      watch:
        - action: rebuild
          path: ./front

networks:
  fullstack-network:
    driver: bridge
