services:
  backend:
    build: ./back
    ports:
      - "5000:5000"
    networks:
      - fullstack-network
    develop:
      watch:
        - action: rebuild
          path: ./back
    # Add logging configuration for backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
      - OTEL_SERVICE_NAME=weather-backend

  frontend:
    build:
      context: ./front
      args:
        - REACT_APP_BACKEND_URL=http://backend:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - fullstack-network
    develop:
      watch:
        - action: rebuild
          path: ./front
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Loki for logs
  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3101:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - fullstack-network
    volumes:
      - loki-data:/loki

  # Tempo for traces
  tempo:
    image: grafana/tempo:2.3.0
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    ports:
      - "3201:3200"   # tempo
      - "4317:4317"   # otlp grpc
    networks:
      - fullstack-network

  # Mimir for metrics
  mimir:
    image: grafana/mimir:2.10.3
    command: [ "-config.file=/etc/mimir.yaml" ]
    volumes:
      - ./mimir/mimir.yaml:/etc/mimir.yaml
      - mimir-data:/tmp/mimir
    ports:
      - "9010:9009"
    networks:
      - fullstack-network

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:v2.48.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - fullstack-network

  # Grafana for visualization
  grafana:
    image: grafana/grafana:10.2.3
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_SERVER_HTTP_PORT=3001
    ports:
      - "3001:3001"
    networks:
      - fullstack-network
    depends_on:
      - loki
      - tempo
      - mimir
      - prometheus

networks:
  fullstack-network:
    driver: bridge

volumes:
  loki-data:
  tempo-data:
  mimir-data:
  grafana-data: