global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:5000']

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']

  - job_name: 'mimir'
    static_configs:
      - targets: ['mimir:9009']
      
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

remote_write:
  - url: http://mimir:9009/api/v1/push
    name: mimir